New hope
stAnger917/practice pull request #11
Opened 2022-03-19 14:08 UTC by stAnger917

2022-03-22 10:40 UTC, rktkov requested changes

2022-03-22 10:40 UTC, rktkov commented on internal/handlers/hadnlers.go
> +package handlers
Опечатка в имени файла

2022-03-22 10:40 UTC, rktkov commented on internal/handlers/hadnlers.go
> +func MyURLHandler(service Service) *URLHandler {
Надо переименовать функцию. Функции должны называться так, чтобы было понятно, что они делают.

2022-03-22 10:40 UTC, rktkov commented on internal/handlers/hadnlers.go
> +			c.String(http.StatusBadRequest, "empty URL in response body denied")
В ошибке кажется слово response не верное. Кажется подразумевается - request

2022-03-22 10:40 UTC, rktkov commented on internal/handlers/hadnlers.go
> +		c.String(201, res)
Лучше использовать константу из пакета.

2022-03-22 10:40 UTC, rktkov commented on internal/handlers/hadnlers.go
> +		c.String(201, res)
Лучше использовать константу.

2022-03-22 10:40 UTC, rktkov commented on internal/handlers/hadnlers.go
> +	if reqContentType == "application/json" {
Я бы код обработки тела запроса в зависимости от типа контента вынес бы в разные внутренние функции. Тем самым сделал бы код самого обработчика более читабельным.

2022-03-22 10:40 UTC, rktkov commented on internal/handlers/hadnlers.go
> +	c.String(307, "redirecting")
Лучше использовать константу.

2022-03-22 10:40 UTC, rktkov commented on internal/handlers/hadnlers.go
> +	id := c.Param("id")
Почему бы не перенести это в начало метода, а потом проверять значение переменной на пустоту.

2022-03-22 10:40 UTC, rktkov commented on internal/server/srv.go
> +func (s *Server) Stop(ctx context.Context) error {
Где вызывается этот метод?

2022-03-22 12:56 UTC, stAnger917 commented on config/config.go
> +	var AppConfig Config
функция InitConfig используется в пакете main =/

2022-03-22 14:44 UTC, stAnger917 commented on internal/service/service.go
> +	BaseURL := "http://localhost:8080/"
большую букву убрал, а на конфиг зашиваться не хотел - чтобы сервис у нас был более независимым

2022-03-22 14:48 UTC, stAnger917 commented on internal/storage/storage.go
> +	s.store[id] = URL
добавил обработку при получении данных запроса, так можно?)

2022-03-22 15:36 UTC, stAnger917 commented on config/config.go
> +type (
исправлено

2022-03-22 15:36 UTC, stAnger917 commented on config/config.go
> +	var AppConfig Config
исправлено

2022-03-22 15:37 UTC, stAnger917 commented on internal/handlers/hadnlers.go
> +		c.String(201, res)
исправлено

2022-03-22 15:37 UTC, stAnger917 commented on internal/handlers/hadnlers.go
> +	if reqContentType == "application/json" {
добавил обработчики

2022-03-22 15:37 UTC, stAnger917 commented on internal/handlers/hadnlers.go
> +	c.String(307, "redirecting")
исправлено

2022-03-22 15:37 UTC, stAnger917 commented on internal/handlers/hadnlers.go
> +	id := c.Param("id")
исправлено

2022-03-22 15:38 UTC, stAnger917 commented on internal/server/srv.go
> +func (s *Server) Stop(ctx context.Context) error {
исправлено, задел на будущее, чуть позднее прикручу

2022-03-23 10:44 UTC, rktkov requested changes

2022-03-23 10:44 UTC, rktkov commented on config/config.go
> +	srvHost, exists := os.LookupEnv("HTTP_HOST")
Можно сделать изящнее: в начале проинициализировать значениями по умолчанию, а по мере считывания из файла конфигурации, заменять на новые значения.

2022-03-23 10:44 UTC, rktkov commented on internal/storage/storage.go
> +	s.store[id] = URL
Это зависит от того, какую логику ты предполагаешь конкретно для сущности "Хранилище", описанной в этом пакете. В независимости от того, кто вызывает метод SaveID, ты допускаешь ситуацию сохранения по пустому ключу?
Если допускаешь, то ничего добавлять не надо. Если не допускаешь,  то стоит добавить проверку.
И еще момент, в прошлый раз не обратил внимание - параметр URL, лучше назвать в нижнем регистре.

2022-03-23 10:44 UTC, rktkov commented on internal/storage/storage_test.go
> +type testStorage struct {
Ты ведь тестируешь интерфейс и логику модуля "Хранилище", его и надо использовать в тесте.
То, что ты дальше в коде инициализируешь внутреннюю переменную реализации модуля - это совсем плохо.
Тесты должны быть написаны таким образом, как будто они ничего не знают о внутренней реализации тестируемого модуля.
Представь себе, что на следующем этапе,  ты вместо хеш-таблицы для хранения данных, начнешь использовать БД. Тогда тебе придется переписывать  код твоих тестов. А такого не должно быть. Задача тестов проверить логику работу, а не детали ее реализации.

2022-03-23 10:44 UTC, rktkov commented on internal/handlers/handlers.go
> +	GetID(url string) string
Вот тут ведь url  в нижнем регистре.

2022-03-23 10:44 UTC, rktkov commented on internal/handlers/handlers.go
> +	reqContentType := checkRequestContentType(c)
Сигнал о том, что получен неподдерживаемый тип тела запроса, лучше возвращать в виде ошибки, а не строковым описанием. В таком случае, читая код, однозначно понятно, что есть вариант получить ошибку.

2022-03-23 10:44 UTC, rktkov commented on internal/handlers/handlers.go
> +	case reqContentType == "unsupported format":
Этот код уйдет в обработчик ошибки.

2022-03-23 10:44 UTC, rktkov commented on internal/service/service.go
> +	baseURL := "http://localhost:8080/"
Я бы это тоже убрал в конфиг.

2022-03-23 10:44 UTC, rktkov commented on internal/service/service.go
> +	id := s.dataStorage.CreateShortURLSign(7)
Логически существование в модуле хранилища действия о получении сокращенной ссылки выглядит не уместным. Кажется, что хранилище должно заниматься управлением данными, а не их логическими преобразовании. 
Мне кажется, что это действие стоит перенести в код сервиса. Тогда в существовании этого слоя обработки становится обоснованным, а то до этого он выгладил как обертка над хранилищем.

2022-03-23 10:44 UTC, rktkov commented on internal/storage/storage.go
> +func (s *Storage) CreateShortURLSign(length int) string {
См. комментарий в файле service.go

2022-03-23 10:54 UTC, stAnger917 commented on internal/storage/storage.go
> +func StringWithCharset(length int, charset string) string {
исправлено

2022-03-23 11:00 UTC, stAnger917 commented on internal/storage/storage.go
> +	s.store[id] = URL
в целом - на данном этапе - допускаю, посмотрим как будут развиваться требования и задания

2022-03-23 11:26 UTC, stAnger917 commented on internal/service/service.go
> +	id := s.dataStorage.CreateShortURLSign(7)
поправил, удивительно что мне самого это не смутило (

2022-03-23 12:24 UTC, stAnger917 commented on internal/storage/storage_test.go
> +type testStorage struct {
исправлено

2022-03-23 12:24 UTC, stAnger917 commented on internal/service/service.go
> +	baseURL := "http://localhost:8080/"
реализовал

2022-03-23 12:25 UTC, stAnger917 commented on internal/service/service.go
> +	BaseURL := "http://localhost:8080/"
поправил - закинул в конфигу

2022-03-23 12:25 UTC, stAnger917 commented on config/config.go
> +	srvHost, exists := os.LookupEnv("HTTP_HOST")
исправил

2022-03-23 17:38 UTC, merged