Sprint2
stAnger917/practice pull request #13
Opened 2022-04-01 12:10 UTC by stAnger917

2022-04-08 08:20 UTC, rktkov requested changes

2022-04-08 08:20 UTC, rktkov commented on internal/storage/storage.go
> +	if val, ok := s.store[id]; ok {
Метод не безопасный с точки зрения работы с разделяемым ресурсом (s) при сценарии работы с несколькими конкурентными обращениями.

2022-04-08 08:20 UTC, rktkov commented on internal/storage/storage.go
>  func (s *Storage) FindURLByID(id string) (string, error) {
Сигнал об отсутствии значения в хранилище стоит возвращать с помощью флага, а не ошибки.

2022-04-10 10:50 UTC, rktkov requested changes

2022-04-10 10:50 UTC, rktkov commented on internal/storage/storage.go
> +//func (s *Storage) SaveID(id, URL string) {
Комментарий не несет смысловой нагрузки. Хранение кода для будущего использования лучше организовать где-то вне репозитория.

2022-04-10 10:50 UTC, rktkov commented on internal/storage/storage.go
> +func (s *Storage) FindURLByID(id string) string {
Пустая строка не является сигналом об отсутствии значения по ключу. Потому что выше в методе сохранения есть возможность сохранить пустую строку по ключу.

2022-04-10 10:50 UTC, rktkov commented on internal/storage/storage.go
> +func NewStorage(filePath string) (*Storage, error) {
Очень нагруженный метод с точки зрения логических шагов. Стоит добавить комментарий к методу, где будет описан алгоритм его работы.

2022-04-11 08:40 UTC, rktkov approved these changes

2022-04-11 11:17 UTC, stAnger917 commented on internal/storage/storage.go
> +	err = appStorage.flush()
запутался уже с этим методом) надо будет его переписать по проще, комментарии обновил

2022-04-11 11:20 UTC, stAnger917 commented on internal/storage/storage.go
>  	if res != "" {
Следует использовать if val, ok := s.store[id]?

2022-04-11 11:20 UTC, merged